name: github pages

on:
  push:
    branches:
    - master
  schedule:
    - cron: '0 0 * * *'

jobs:
  build-deploy:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@master
      with:
        submodules: true

    - name: setup node environment
      uses: actions/setup-node@v1
      with:
        node-version: '10.16'

    - name: install npm dependencies
      run: |
        npm install -g tuture
        npm install
        npm run buildTutorials
        export HEXO_ALGOLIA_INDEXING_KEY=${{ HEXO_ALGOLIA_INDEXING_KEY }}
        npm run clean
        npm run algolia
        npm run build

    - name: deploy
      uses: peaceiris/actions-gh-pages@v2.4.0
      env:
        ACTIONS_DEPLOY_KEY: ${{ secrets.ACTIONS_DEPLOY_KEY }}
        PUBLISH_BRANCH: gh-pages
        PUBLISH_DIR: ./public